---
title: "Clean"
author: "Micah Turner"
date: "2023-09-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document is intended to import the data and clean it for downstream analytics and visualization.

# Load Libraries
```{r}
## Step 1
library(tidyverse)
library(data.table)
```

# Import CSV
```{r}
dat <- read.csv("2023_02_summary.csv", header=FALSE)
```

# Extract vector of Employee IDs
```{r}
employee_ID <- pull(dat,V2)
employee_ID <- unique(employee_ID)
employee_ID <- employee_ID[3:length(employee_ID)]
```

# Clean imported csv to create tidy dataframes for each of the 4 metrics 
```{R}
## Remove rows below Employee_Id in data
tempVar1 <- length(employee_ID)+3
tempVar2 <- nrow(dat)
dat <- dat[-c(tempVar1:tempVar2),]

## Remove commas, which if present returns NA upon conversion to numeric class (e.g 1,215 to 1215)
tempVar3 <- c(3:length(dat))
dat[tempVar3] <- lapply(dat[tempVar3], gsub, pattern =",", replacement="")

## Remove % symbols, which if present returns NA upon conversion to numeric class (e.g. 98% = 98)
dat[tempVar3] <- lapply(dat[tempVar3], gsub, pattern ="%", replacement="")

## Create completed moves (cms) dataframe
cms_v1 <- dat[, dat[2, ] == "Completed Moves"]
cms_v2 <- dat[, c(2,length(dat)-3)]
cms_v3 <- cbind(cms_v2, cms_v1)

## Create moves per hour (mph) dataframe
mph_v1 <- dat[, dat[2, ] == "MPH"]
mph_v2 <- dat[, c(2,length(dat)-1)]
mph_v3 <- cbind(mph_v2, mph_v1)

## Create on time percent (otp) dataframe
otp_v1 <- dat[, dat[2, ] == "On-Time Moves "]
otp_v2 <- dat[, c(2,length(dat))]
otp_v3 <- cbind(otp_v2, otp_v1)

## Create hours Worked (hrw) dataframe
hrw_v1 <- dat[, dat[2, ] == "Hours Worked"]
hrw_v2 <- dat[, c(2,length(dat)-2)]
hrw_v3 <- cbind(hrw_v2, hrw_v1)

## Make the date row the header for cms, mph, otp, and hrw dataframes
cms_v4 <- cms_v3
colnames(cms_v4) <- cms_v3[1, ]
cms_v4 = cms_v4[-1,]

mph_v4 <- mph_v3
colnames(mph_v4) <- mph_v3[1, ]
mph_v4 = mph_v4[-1,]

otp_v4 <- otp_v3
colnames(otp_v4) <- otp_v3[1, ]
otp_v4 = otp_v4[-1,]

hrw_v4 <- hrw_v3
colnames(hrw_v4) <- hrw_v3[1, ]
hrw_v4 = hrw_v4[-1,]

## Label the column Employee ID column
colnames(cms_v4)[1] <- "Employee_ID"
colnames(mph_v4)[1] <- "Employee_ID"
colnames(otp_v4)[1] <- "Employee_ID"
colnames(hrw_v4)[1] <- "Employee_ID"

## Label the Total column 
colnames(cms_v4)[2] <- "Total"
colnames(mph_v4)[2] <- "Total"
colnames(otp_v4)[2] <- "Total"
colnames(hrw_v4)[2] <- "Total"

## Change the data class from character to numeric
c4 <- c(2:length(cms_v4))
cms_v4[ ,c4] <- apply(cms_v4[ ,c4], 2, function(x) as.numeric(as.character(x)))
mph_v4[ ,c4] <- apply(mph_v4[ ,c4], 2, function(x) as.numeric(as.character(x)))
otp_v4[ ,c4] <- apply(otp_v4[ ,c4], 2, function(x) as.numeric(as.character(x)))
hrw_v4[ ,c4] <- apply(hrw_v4[ ,c4], 2, function(x) as.numeric(as.character(x)))

## Add a row with the calculated mean 

### Copy dataframe
cms_v5 <- cms_v4
mph_v5 <- mph_v4
otp_v5 <- otp_v4

### Calculate mean of all numeric columns
cms_v5 <- cms_v4 %>% summarize_if(is.numeric, mean, na.rm = TRUE)
mph_v5 <- mph_v4 %>% summarize_if(is.numeric, mean, na.rm = TRUE)
otp_v5 <- otp_v4 %>% summarize_if(is.numeric, mean, na.rm = TRUE)

### Label the new row 
Employee_ID <- "Average"
cms_v5$Employee_ID <- Employee_ID
mph_v5$Employee_ID <- Employee_ID
otp_v5$Employee_ID <- Employee_ID

### Reorder A number column from last to first
cms_v5 <- cms_v5[, c(length(cms_v5),1:length(cms_v5)-1)]
mph_v5 <- mph_v5[, c(length(mph_v5),1:length(mph_v5)-1)]
otp_v5 <- otp_v5[, c(length(otp_v5),1:length(otp_v5)-1)]

### In the darkness bind them
cms_v6 <- rbind(cms_v4,cms_v5)
mph_v6 <- rbind(mph_v4,mph_v5)
otp_v6 <- rbind(otp_v4,otp_v5)

### Round to appropriate digit
cms_v7 <- cms_v6 %>% mutate(across(is.numeric, round, digits=1))
mph_v7 <- mph_v6 %>% mutate(across(is.numeric, round, digits=1))
otp_v7 <- otp_v6 %>% mutate(across(is.numeric, round, digits=1))

## Clean up variable names
cms <- cms_v7
mph <- mph_v7
otp <- otp_v7
hrw <- hrw_v4
```

# Employees (derived from schedule)
```{r}
# 590 Employee Reference Table
names <- c("Shonda Johnson","Alandrea Smith","Joe Juarez","Thad Schmitz","James Wood","Alex Marquette","Jon Naylor","Cody Bertram","Tom Nie","Reece Gilbert","Aaron Sasse","Raymond Wiech","Thomas Oetker","Curt Johnson","Wyatt Catron","Rick Wharton","Joe Volker")
driver_ID <- c("A633224","A634341","A639084","A649672","A582797","A651095","A649670","A650934","A593317","A642379","A617437","A648278","A644891","A639650","A641937","A642929","A650739")
employees <- data.frame(names,driver_ID)

#Employee ID's by shift
a1 <- c("A633224","A634341","A639084","A649672")
a2 <- c("A582797","A651095","A649670","A650934")
b1 <- c("A593317","A642379","A617437","A648278","A644891")
b2 <- c("A639650","A641937","A642929","A650739")

```

# Categorize by Shift
```{r}
## Shift A1
cms_a1 <- subset(cms, employee_ID %in% a1)
mph_a1 <- subset(mph, employee_ID %in% a1)
otp_a1 <- subset(otp, employee_ID %in% a1)
hrw_a1 <- subset(hrw, employee_ID %in% a1)

##Shift A2
cms_a2 <- subset(cms, employee_ID %in% a2)
mph_a2 <- subset(mph, employee_ID %in% a2)
otp_a2 <- subset(otp, employee_ID %in% a2)
hrw_a2 <- subset(hrw, employee_ID %in% a2)

##Shift B1
cms_b1 <- subset(cms, employee_ID %in% b1)
mph_b1 <- subset(mph, employee_ID %in% b1)
otp_b1 <- subset(otp, employee_ID %in% b1)
hrw_b1 <- subset(hrw, employee_ID %in% b1)

##Shift B2
cms_b2 <- subset(cms, employee_ID %in% b2)
mph_b2 <- subset(mph, employee_ID %in% b2)
otp_b2 <- subset(otp, employee_ID %in% b2)
hrw_b2 <- subset(hrw, employee_ID %in% b2)
```

# Add cms, mph, and otp mean values to shifts
```{r}
##Calculate the means
cms_a1_mean <- cms_a1 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

cms_a2_mean <- cms_a2 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

cms_b1_mean <- cms_b1 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

cms_b2_mean <- cms_b2 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

mph_a1_mean <- mph_a1 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

mph_a2_mean <- mph_a2 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

mph_b1_mean <- mph_b1 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

mph_b2_mean <- mph_b2 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

otp_a1_mean <- otp_a1 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

otp_a2_mean <- otp_a2 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

otp_b1_mean <- otp_b1 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

otp_b2_mean <- otp_b2 %>%
        select(-c(1,2)) %>%
  summarize_if(is.numeric, mean, na.rm = TRUE)

## Add columns back to rbind
add_columns_back <- list(Employee_ID = "Average", Total = NA)
add_columns_back <- as.data.frame(add_columns_back)

## In the darkness bind them
cms_a1_mean <- cbind(add_columns_back,cms_a1_mean)
cms_a1 <- rbind(cms_a1,cms_a1_mean)
cms_a1 <- cms_a1 %>% mutate(across(is.numeric, round, digits=1))

cms_a2_mean <- cbind(add_columns_back,cms_a2_mean)
cms_a2 <- rbind(cms_a2,cms_a2_mean)
cms_a2 <- cms_a2 %>% mutate(across(is.numeric, round, digits=1))

cms_b1_mean <- cbind(add_columns_back,cms_b1_mean)
cms_b1 <- rbind(cms_b1,cms_b1_mean)
cms_b1 <- cms_b1 %>% mutate(across(is.numeric, round, digits=1))

cms_b2_mean <- cbind(add_columns_back,cms_b2_mean)
cms_b2 <- rbind(cms_b2,cms_b2_mean)
cms_b2 <- cms_b2 %>% mutate(across(is.numeric, round, digits=1))

mph_a1_mean <- cbind(add_columns_back,mph_a1_mean)
mph_a1 <- rbind(mph_a1,mph_a1_mean)
mph_a1 <- mph_a1 %>% mutate(across(is.numeric, round, digits=1))

mph_a2_mean <- cbind(add_columns_back,mph_a2_mean)
mph_a2 <- rbind(mph_a2,mph_a2_mean)
mph_a2 <- mph_a2 %>% mutate(across(is.numeric, round, digits=1))

mph_b1_mean <- cbind(add_columns_back,mph_b1_mean)
mph_b1 <- rbind(mph_b1,mph_b1_mean)
mph_b1 <- mph_b1 %>% mutate(across(is.numeric, round, digits=1))

mph_b2_mean <- cbind(add_columns_back,mph_b2_mean)
mph_b2 <- rbind(mph_b2,mph_b2_mean)
mph_b2 <- mph_b2 %>% mutate(across(is.numeric, round, digits=1))

otp_a1_mean <- cbind(add_columns_back,otp_a1_mean)
otp_a1 <- rbind(otp_a1,otp_a1_mean)
otp_a1 <- otp_a1 %>% mutate(across(is.numeric, round, digits=1))

otp_a2_mean <- cbind(add_columns_back,otp_a2_mean)
otp_a2 <- rbind(otp_a2,otp_a2_mean)
otp_a2 <- otp_a2 %>% mutate(across(is.numeric, round, digits=1))

otp_b1_mean <- cbind(add_columns_back,otp_b1_mean)
otp_b1 <- rbind(otp_b1,otp_b1_mean)
otp_b1 <- otp_b1 %>% mutate(across(is.numeric, round, digits=1))

otp_b2_mean <- cbind(add_columns_back,otp_b2_mean)
otp_b2 <- rbind(otp_b2,otp_b2_mean)
otp_b2 <- otp_b2 %>% mutate(across(is.numeric, round, digits=1))

```

## Pivot
```{r}
### Pivot Longer
test <- cms_a1 %>%
        pivot_longer(
                cols = !"Employee_ID",
                names_to = "Date",
                values_to = "Count"
        )
### Pivot Wider
test <- test %>%
        pivot_wider(
                names_from = "Employee_ID",
                values_from = "Count"
        )
### Remove Total Row
test <- test[-1,]
View(test)

```

## Test Visualization
```{r}
test2 <- mph_a1[,-2] %>%
        pivot_longer(
                cols = !"Employee_ID",
                names_to = "Date",
                values_to = "Count",

        )
test2$Date <- mdy(test2$Date)
test2 <- as.data.frame(test2)
viz_test <- test2 %>%
        filter(Employee_ID == c("A632200","Average")) %>%
        ggplot(aes(x=Date,y=Count, color = Employee_ID))+
        geom_point(size=3)+
        geom_line(size=1)+
        geom_hline(yintercept = 5, color = "green") +
        scale_color_manual(values = c("red", "blue")) +
        labs(y="Moves/Hr",title = "Moves per Hour: A632200 & Shift Average (A1)")+
        theme_light()
viz_test


```

```{r}
test2 <- cms_a1[,-2] %>%
        pivot_longer(
                cols = !"Employee_ID",
                names_to = "Date",
                values_to = "Count",
                values_drop_na = TRUE
        )
test2$Date <- mdy(test2$Date)

```



```{r}
#Employee ID's by shift
        a1 <- c("A633224","A634341","A639084","A649672")
        a2 <- c("A582797","A651095","A649670","A650934")
        b1 <- c("A593317","A642379","A617437","A648278","A644891")
        b2 <- c("A639650","A641937","A642929","A650739")

mph_viz <- function(shift,id){
        
# Extract individual metric from dataset
        v1 <- dat[, dat[2, ] == "MPH"]
        v2 <- dat[, c(2,length(dat)-3)]
        v3 <- cbind(v2, v1)

# Make the date row the header
        v4 <- v3
        colnames(v4) <- v3[1, ]

# Label the Employee ID column
        colnames(v4)[1] <- "Employee_ID"

# Label the Total column 
        colnames(v4)[2] <- "Total"
        
# Remove first 2 rows
                v4 = v4[-c(1:2),]
        
# Change the data class from character to numeric
        c1 <- c(2:length(v4))
        v4[ ,c1] <- apply(v4[ ,c1], 2, function(x) as.numeric(as.character(x)))
        

# Filter by shift
        v5 <- v4 %>% filter(Employee_ID %in% shift)

# Calculate shift mean
        v5_mean <- v5 %>%
                select(-c(1,2)) %>%
                        summarize_if(is.numeric, mean, na.rm = TRUE)
        
# Add columns back to rbind
        add_columns_back <- list(Employee_ID = "Average", Total = NA)
        add_columns_back <- as.data.frame(add_columns_back)
        
# In the darkness bind them
        v5_mean <- cbind(add_columns_back,v5_mean)
        v6 <- rbind(v5,v5_mean)
        v6 <- v6 %>% mutate(across(is.numeric, round, digits=1))

# Pivot
        v7 <- v6[,-2] %>%
                pivot_longer(
                        cols = !"Employee_ID",
                        names_to = "Date",
                        values_to = "Count",
        )

# Convert Date column to date data-class
        v7$Date <- mdy(v7$Date)
        v7 <- as.data.frame(v7)

# Filter by Employee ID        
        v8 <- v7 %>% filter(Employee_ID %in% c(id,"Average"))
        
# Remove NA and NAN values
        v9 <- v8 %>% filter(!is.na(Count))
        
v10 <- v9 %>%
        ggplot(aes(x=Date,y=Count, color = Employee_ID))+
        geom_point(size=2)+
        geom_line(size=.5)+
        scale_x_date(
                date_breaks = "2 days",
                date_minor_breaks = "1 day",
                date_labels = "%d"
                )+
        geom_hline(yintercept = 5, color = "green") +
        scale_color_manual(values = c("red", "blue")) +
        labs(y="MPH",title = "Monthly Moves/Hr with Shift Average")+
        theme_light()
v10     
}
```

  